# Generated by Django 5.2.8 on 2025-11-11 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catigory',
            new_name='Category',
        ),
        migrations.AlterField(
            model_name='product',
            name='procuct_stock',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('old_stock', 'ស្តុកចាស់'), ('new_stock', 'ស្តុកថ្មី')], default='old_stock', max_length=20),
        ),
    ]
