# Generated by Django 5.2.8 on 2025-11-12 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_catigory_category_alter_product_procuct_stock_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='procuct_stock',
            new_name='product_stock',
        ),
    ]
