# Generated by Django 5.2.8 on 2025-11-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_procuct_stock_product_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_stock',
            field=models.IntegerField(),
        ),
    ]
