# Generated by Django 5.2.8 on 2025-11-14 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_product_product_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='catigory_name',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='catigory_name',
            new_name='category_name',
        ),
    ]
